name: Nightly Build

on:
#  - push
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  build-rules:
    environment: Production
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Config Git user name and email
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Generate the latest rules
        run: bash factory/auto_build.sh

